name: cabosat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider:
  http:
  intl:
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  open_file:
  font_awesome_flutter:
  firebase_messaging: ^15.1.5
  firebase_core:
  flutter_local_notifications:
  url_launcher:
  flutter_secure_storage:
  sqflite:
  cloud_firestore: ^5.5.1
  connectivity_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OktaNeue
      fonts:
        - asset: assets/fonts/OktaNeue-Regular.ttf
          weight: 400
        - asset: assets/fonts/OktaNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/OktaNeue-Black.ttf
          weight: 900
